spring:
  application:
    name: gatekeeper

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: AuthEndFilter
              args:
                baseMessage: Spring Cloud Gateway Auth End Filter
                preLogger: true
                postLogger: true
#        - id: user-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/users/**
#          filters:
#            - name: AuthFilter
        - id: whiskey-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/whiskeys/**
          filters:
            - name: AuthFilter
        - id: main-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
          filters:
            - name: AuthFilter
auth:
  header:
    user-id: X-Kisswe-User-Id
  signing-key:
    type: JKS
    filename: signature-keystore-dev.jks
    password: Admin123Admin123
    alias: kisswe-jwt-signature-dev-key
